org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=titanium
mod.name=Titanium
mod.group=net.rotgruengelb
mod.version=0.1.0
mod.channel_tag=-alpha.1
mod.authors=NanoBot\u03A3, rotgruengelb, Steaf23
mod.contributors=NanoBot\u03A3, rotgruengelb, Steaf23, Oddity2004
mod.license=MIT
mod.description=A mod that expands upon the End with three diverse and expansive biomes. Delve into the roots of the universe, whether it be flora or code.
mod.sources_url=https://github.com/rotgruengelb/stonecutter-mod-template
mod.homepage_url=https://github.com/rotgruengelb/stonecutter-mod-template
mod.issues_url=https://github.com/rotgruengelb/stonecutter-mod-template/issues
mod.discord_url=https://discord.gg/aunYJB4wz9

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]

publish.modrinth=
publish.curseforge=
publish.github=true
